# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 648)
        MainWindow.setStyleSheet("/*\n"
"  aqua.qss (version 0.1)\n"
"  released under the MIT license (https://opensource.org/licenses/MIT)\n"
"  www.poketcode.com - March 2016\n"
"*/\n"
"\n"
"/**** QWidget (enabled) ****/\n"
"QWidget\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  color: rgb(220,220,220);\n"
"  font-size: 11px;\n"
"  outline: none;\n"
"}\n"
"\n"
"/**** QWidget (disabled) ****/\n"
"QWidget:disabled\n"
"{\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QPushButton (enabled) ****/\n"
"QPushButton\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(120,120,120), stop: 1 rgb(80,80,80));\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(230,230,230);\n"
"  padding: 4px 8px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"  padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"/**** QPushButton (checkable) ****/\n"
"QPushButton:checked\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(40,150,200), stop: 1 rgb(90,200,255));\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"QPushButton:checked:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"/**** QPushButton (disabled) ****/\n"
"QPushButton:disabled\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(160,160,160), stop: 1 rgb(120,120,120));\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QToolButton (enabled) ****/\n"
"QToolButton\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(120,120,120), stop: 1 rgb(80,80,80));\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px 8px;\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"  padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"/**** QToolButton (checkable) ****/\n"
"QToolButton:checked\n"
"{\n"
"  border-color: transparent;\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(40,150,200), stop: 1 rgb(90,200,255));\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"/**** QToolButton (disabled) ****/\n"
"QToolButton:disabled\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(160,160,160), stop: 1 rgb(120,120,120));\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QRadioButton (enabled) ****/\n"
"QRadioButton\n"
"{\n"
"  background-color: transparent;\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"  border: 1px solid rgb(20,20,20);\n"
"  border-radius: 7px;\n"
"  width: 14px;\n"
"  height: 14px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(120,120,120), stop: 1 rgb(80,80,80));\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(80,80,80), stop: 1 rgb(120,120,120));\n"
"  image: url(images/radiobutton_checked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover,\n"
"QRadioButton::indicator:checked:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:pressed,\n"
"QRadioButton::indicator:checked:pressed\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"}\n"
"\n"
"/**** QRadioButton (disabled) ****/\n"
"QRadioButton:disabled\n"
"{\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QRadioButton::indicator:disabled\n"
"{\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:disabled\n"
"{\n"
"  image: url(images/radiobutton_checked_disabled.png);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QCheckBox (enabled) ****/\n"
"QCheckBox\n"
"{\n"
"  background-color: transparent;\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px 8px;\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"  border: 1px solid rgb(20,20,20);\n"
"  width: 14px;\n"
"  height: 14px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(120,120,120), stop: 1 rgb(80,80,80));\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(80,80,80), stop: 1 rgb(120,120,120));\n"
"  image: url(images/checkbox_checked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(80,80,80), stop: 1 rgb(120,120,120));\n"
"  image: url(images/checkbox_indeterminate.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover,\n"
"QCheckBox::indicator:checked:hover,\n"
"QCheckBox::indicator:indeterminate:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed,\n"
"QCheckBox::indicator:checked:pressed,\n"
"QCheckBox::indicator:indeterminate:pressed\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"}\n"
"\n"
"/**** QCheckBox (disabled) ****/\n"
"QCheckBox:disabled\n"
"{\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"  image: url(images/checkbox_checked_disabled.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:disabled\n"
"{\n"
"  image: url(images/checkbox_indeterminate_disabled.png);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QListView (enabled) ****/\n"
"QListView\n"
"{\n"
"  alternate-background-color: rgb(110,110,110);\n"
"  background-color: rgb(100,100,100);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QListView QLineEdit\n"
"{\n"
"  padding: -1 0 0 0;\n"
"}\n"
"\n"
"QListView::item:hover,\n"
"QListView::item:selected:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"  color: white;\n"
"}\n"
"\n"
"QListView::item:selected\n"
"{\n"
"  background-color: rgb(90,200,255);\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"/**** QListView (disabled) ****/\n"
"QListView:disabled\n"
"{\n"
"  alternate-background-color: rgb(130,130,130);\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QListView::item:selected:disabled\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QTableView (enabled) ****/\n"
"QTableView\n"
"{\n"
"  alternate-background-color: rgb(110,110,110);\n"
"  background-color: rgb(100,100,100);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QTableView QLineEdit\n"
"{\n"
"  padding: -1 0 0 0;\n"
"}\n"
"\n"
"QTableView::item:hover,\n"
"QTableView::item:selected:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"  color: white;\n"
"}\n"
"\n"
"QTableView::item:selected\n"
"{\n"
"  background-color: rgb(90,200,255);\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"QTableView QTableCornerButton::section\n"
"{\n"
"  background-color: rgb(60,60,60);\n"
"  border: 1px inset rgb(60,60,60);\n"
"}\n"
"\n"
"/**** QTableView (disabled) ****/\n"
"QTableView:disabled\n"
"{\n"
"  alternate-background-color: rgb(130,130,130);\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QTableView::item:selected:disabled\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QTableView QTableCornerButton::section:disabled\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  border: 1px inset rgb(80,80,80);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QHeaderView (enabled) ****/\n"
"QHeaderView\n"
"{\n"
"   background-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"   background-color: rgb(60,60,60);\n"
"   border: 1px inset rgb(60,60,60);\n"
"   color: rgb(220,220,220);\n"
"   padding: 4px;\n"
"}\n"
"\n"
"/**** QHeaderView (disabled) ****/\n"
"QHeaderView:disabled\n"
"{\n"
"   background-color: rgb(80,80,80);\n"
"}\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"   background-color: rgb(80,80,80);\n"
"   color: rgb(190,190,190);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QTreeView (enabled) ****/\n"
"QTreeView\n"
"{\n"
"  alternate-background-color: rgb(110,110,110);\n"
"  background-color: rgb(100,100,100);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QTreeView QLineEdit\n"
"{\n"
"  padding: -1 0 0 0;\n"
"}\n"
"\n"
"QTreeView::item:hover,\n"
"QTreeView::item:selected:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"  color: white;\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"  background-color: rgb(90,200,255);\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item\n"
"{\n"
"  border-image: url(images/vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item\n"
"{\n"
"  border-image: url(images/branch-more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item\n"
"{\n"
"  border-image: url(images/branch-end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:!has-siblings,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"  image: url(images/branch-closed.png);\n"
"  margin: 3px;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"  image: url(images/branch-open.png);\n"
"  margin: 3px;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:!has-siblings:hover,\n"
"QTreeView::branch:closed:has-children:has-siblings:hover\n"
"{\n"
"  image: url(images/branch-closed_hover.png);\n"
"  margin: 3px;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings:hover,\n"
"QTreeView::branch:open:has-children:has-siblings:hover\n"
"{\n"
"  image: url(images/branch-open_hover.png);\n"
"  margin: 3px;\n"
"}\n"
"\n"
"/**** QTreeView (disabled) ****/\n"
"QTreeView:disabled\n"
"{\n"
"  alternate-background-color: rgb(130,130,130);\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QTreeView::item:selected:disabled\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QColumnView (enabled) ****/\n"
"QColumnView\n"
"{\n"
"  alternate-background-color: rgb(110,110,110);\n"
"  background-color: rgb(100,100,100);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QColumnView QLineEdit\n"
"{\n"
"  padding: -1 0 0 0;\n"
"}\n"
"\n"
"QColumnView::item:hover,\n"
"QColumnView::item:selected:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"  color: white;\n"
"}\n"
"\n"
"QColumnView::item:selected\n"
"{\n"
"  background-color: rgb(90,200,255);\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"/**** QColumnView (disabled) ****/\n"
"QColumnView:disabled\n"
"{\n"
"  alternate-background-color: rgb(130,130,130);\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QColumnView::item:selected:disabled\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QGroupBox (enabled) ****/\n"
"QGroupBox\n"
"{\n"
"  background-color: transparent;\n"
"  background-clip: margin;\n"
"  border: 1px solid rgb(20,20,20);\n"
"  border-radius: 4px;\n"
"  margin-top: 10px;\n"
"  padding-top: 4px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"  padding: 2px 8px;\n"
"  subcontrol-origin: margin;\n"
"  subcontrol-position: top center;\n"
"}\n"
"\n"
"QGroupBox::indicator\n"
"{\n"
"  border: 1px solid rgb(20,20,20);\n"
"  width: 14px;\n"
"  height: 14px;\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(120,120,120), stop: 1 rgb(80,80,80));\n"
"}\n"
"\n"
"QGroupBox::indicator:checked\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(80,80,80), stop: 1 rgb(120,120,120));\n"
"  image: url(images/checkbox_checked.png);\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked:hover,\n"
"QGroupBox::indicator:checked:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked:pressed,\n"
"QGroupBox::indicator:checked:pressed\n"
"{\n"
"  border: 1px solid rgb(90,200,255);\n"
"}\n"
"\n"
"/**** QGroupBox (disabled) ****/\n"
"QGroupBox:disabled\n"
"{\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QGroupBox::indicator:disabled\n"
"{\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QGroupBox::indicator:checked:disabled\n"
"{\n"
"  image: url(images/checkbox_checked_disabled.png);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QScrollArea (enabled) ****/\n"
"QScrollArea\n"
"{\n"
"  background-color: rgb(100,100,100);\n"
"  border: 1px solid rgb(20,20,20);\n"
"}\n"
"\n"
"/**** QScrollArea (disabled) ****/\n"
"QScrollArea:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QToolBox (enabled) ****/\n"
"QToolBox\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QToolBox::tab\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(120,120,120), stop: 1 rgb(80,80,80));\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"}\n"
"\n"
"QToolBox::tab:hover,\n"
"QToolBox::tab:selected:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QToolBox::tab:selected\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(40,150,200), stop: 1 rgb(90,200,255));\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"QToolBox QScrollArea\n"
"{\n"
"  background-color: rgb(100,100,100);\n"
"  border: 0px solid transparent;\n"
"}\n"
"\n"
"/**** QToolBox (disabled) ****/\n"
"QToolBox::tab:disabled\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(160,160,160), stop: 1 rgb(120,120,120));\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QToolBox QScrollArea:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: transparent;\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QTabWidget (enabled) ****/\n"
"QTabWidget\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QTabWidget::pane\n"
"{\n"
"  border: 1px solid rgb(20,20,20);\n"
"}\n"
"\n"
"/**** QTabWidget (disabled) ****/\n"
"QTabWidget::pane:disabled\n"
"{\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QTabBar (enabled) ****/\n"
"QTabBar\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(120,120,120), stop: 1 rgb(80,80,80));\n"
"  border: 1px solid rgb(60,60,60);\n"
"  border-bottom: 0;\n"
"  border-top-right-radius: 12px;\n"
"  color: rgb(220,220,220);\n"
"  margin-right: 2px;\n"
"  padding: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(40,150,200), stop: 1 rgb(90,200,255));\n"
"  border-color: rgb(20,20,20);\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"QTabBar::tab:selected:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"  color: rgb(220,220,220);\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"  margin-top: 4px;\n"
"}\n"
"\n"
"QTabBar::tear\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QTabBar QToolButton\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  border: 1px solid transparent;\n"
"  padding: 0px;\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow\n"
"{\n"
"  image: url(images/right_arrow);\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow\n"
"{\n"
"  image: url(images/left_arrow);\n"
"}\n"
"\n"
"QTabBar QToolButton:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QTabBar QToolButton:pressed\n"
"{\n"
"  border-color: transparent;\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:pressed\n"
"{\n"
"  image: url(images/right_arrow_pressed);\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:pressed\n"
"{\n"
"  image: url(images/left_arrow_pressed);\n"
"}\n"
"\n"
"/**** QTabBar (disabled) ****/\n"
"QTabBar:disabled\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab:disabled\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(160,160,160), stop: 1 rgb(120,120,120));\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QTabBar::tab:selected:disabled\n"
"{\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QTabBar QToolButton:disabled\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  border-color: transparent;\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:disabled\n"
"{\n"
"  image: url(images/left_arrow_disabled);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled\n"
"{\n"
"  image: url(images/right_arrow_disabled);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QDockWidget (enabled) ****/\n"
"QDockWidget\n"
"{\n"
"  background-color: rgb(110,110,110);\n"
"  color: rgb(20,20,20);\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button\n"
"{\n"
"  background-color: transparent;\n"
"  border: 1px solid transparent;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover,\n"
"QDockWidget::float-button:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed,\n"
"QDockWidget::float-button:pressed\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"  padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QDockWidget > QWidget\n"
"{\n"
"  background-color: rgb(90,90,90);\n"
"}\n"
"\n"
"/**** QDockWidget (disabled) ****/\n"
"QDockWidget:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QDockWidget > QWidget:disabled\n"
"{\n"
"  background-color: rgb(100,100,100);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QComboBox (enabled) ****/\n"
"QComboBox\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px 8px;\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"  image: url(images/dropdown.png);\n"
"  margin: 4px;\n"
"  width: 14px;\n"
"  height: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on\n"
"{\n"
"  image: url(images/dropdown_on.png);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  padding: 4px;\n"
"}\n"
"\n"
"/**** QComboBox (editable) ****/\n"
"QComboBox:editable\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  padding: 4px;\n"
"}\n"
"\n"
"QComboBox:editable:focus\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"}\n"
"\n"
"/**** QComboBox (disabled) ****/\n"
"QComboBox:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QComboBox::drop-down:disabled\n"
"{\n"
"  image: url(images/dropdown_disabled.png);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QLineEdit (enabled) ****/\n"
"QLineEdit\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px;\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"}\n"
"\n"
"/**** QLineEdit (disabled) ****/\n"
"QLineEdit:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QTextEdit (enabled) ****/\n"
"QTextEdit\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px;\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"}\n"
"\n"
"/**** QTextEdit (disabled) ****/\n"
"QTextEdit:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QPlainTextEdit (enabled) ****/\n"
"QPlainTextEdit\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px;\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QPlainTextEdit:focus\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"}\n"
"\n"
"/**** QPlainTextEdit (disabled) ****/\n"
"QPlainTextEdit:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QSpinBox, QDoubleSpinBox, QTimeEdit, QDateEdit and QDateTimeEdit (enabled) ****/\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QTimeEdit,\n"
"QDateEdit,\n"
"QDateTimeEdit\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px;\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus,\n"
"QTimeEdit:focus,\n"
"QDateEdit:focus,\n"
"QDateTimeEdit:focus\n"
"{\n"
"  border-color: rgb(90,200,255);\n"
"}\n"
"\n"
"QSpinBox::up-button,\n"
"QDoubleSpinBox::up-button,\n"
"QTimeEdit::up-button,\n"
"QDateEdit::up-button,\n"
"QDateTimeEdit::up-button\n"
"{\n"
"  image: url(images/spinup.png);\n"
"  width: 16px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover,\n"
"QDoubleSpinBox::up-button:hover,\n"
"QTimeEdit::up-button:hover,\n"
"QDateEdit::up-button:hover,\n"
"QDateTimeEdit::up-button:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed,\n"
"QDoubleSpinBox::up-button:pressed,\n"
"QTimeEdit::up-button:pressed,\n"
"QDateEdit::up-button:pressed,\n"
"QDateTimeEdit::up-button:pressed\n"
"{\n"
"  image: url(images/spinup_pressed.png);\n"
"}\n"
"\n"
"QSpinBox::down-button,\n"
"QDoubleSpinBox::down-button,\n"
"QTimeEdit::down-button,\n"
"QDateEdit::down-button,\n"
"QDateTimeEdit::down-button\n"
"{\n"
"  image: url(images/spindown.png);\n"
"  width: 16px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover,\n"
"QDoubleSpinBox::down-button:hover,\n"
"QTimeEdit::down-button:hover,\n"
"QDateEdit::down-button:hover,\n"
"QDateTimeEdit::down-button:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed,\n"
"QDoubleSpinBox::down-button:pressed,\n"
"QTimeEdit::down-button:pressed,\n"
"QDateEdit::down-button:pressed,\n"
"QDateTimeEdit::down-button:pressed\n"
"{\n"
"  image: url(images/spindown_pressed.png);\n"
"}\n"
"\n"
"/**** QSpinBox, QDoubleSpinBox, QTimeEdit, QDateEdit and QDateTimeEdit (disabled) ****/\n"
"QSpinBox:disabled,\n"
"QDoubleSpinBox:disabled,\n"
"QTimeEdit:disabled,\n"
"QDateEdit:disabled,\n"
"QDateTimeEdit:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"QSpinBox::up-button:disabled,\n"
"QDoubleSpinBox::up-button:disabled,\n"
"QTimeEdit::up-button:disabled,\n"
"QDateEdit::up-button:disabled,\n"
"QDateTimeEdit::up-button:disabled\n"
"{\n"
"  image: url(images/spinup_disabled.png);\n"
"}\n"
"\n"
"QSpinBox::down-button:disabled,\n"
"QDoubleSpinBox::down-button:disabled,\n"
"QTimeEdit::down-button:disabled,\n"
"QDateEdit::down-button:disabled,\n"
"QDateTimeEdit::down-button:disabled\n"
"{\n"
"  image: url(images/spindown_disabled.png);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QDial (enabled) ****/\n"
"QDial\n"
"{\n"
"  background-color: rgb(20,20,20);\n"
"  selection-background-color: rgb(90,200,255);\n"
"}\n"
"\n"
"/**** QDial (disabled) ****/\n"
"QDial:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QScrollBar (enabled) ****/\n"
"QScrollBar\n"
"{\n"
"  background-color: transparent;\n"
"  border: 1px solid rgb(10,10,10);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QScrollBar::handle\n"
"{\n"
"  background-color: rgb(90,200,255);\n"
"  border-radius: 3px;\n"
"  min-width: 16px;\n"
"  min-height: 16px;\n"
"  margin: 1px;\n"
"}\n"
"\n"
"QScrollBar::add-line,\n"
"QScrollBar::sub-line\n"
"{\n"
"  border: 1px solid transparent;\n"
"  border-radius: 10px;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:hover,\n"
"QScrollBar::add-line:pressed,\n"
"QScrollBar::sub-line:hover,\n"
"QScrollBar::sub-line:pressed\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"QScrollBar::add-page,\n"
"QScrollBar::sub-page\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"/**** QScrollBar (horizontal) ****/\n"
"QScrollBar:horizontal\n"
"{\n"
"  height: 20px;\n"
"  margin: 5px 23px 5px 23px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"  min-width: 30px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"  width: 20px;\n"
"  subcontrol-position: right;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"  width: 20px;\n"
"  subcontrol-position: left;\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"{\n"
"  image: url(images/scrollbar_left_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal:pressed\n"
"{\n"
"  image: url(images/scrollbar_left_arrow_pressed.png);\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal\n"
"{\n"
"  image: url(images/scrollbar_right_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal:pressed\n"
"{\n"
"  image: url(images/scrollbar_right_arrow_pressed.png);\n"
"}\n"
"\n"
"/**** QScrollBar (vertical) ****/\n"
"QScrollBar:vertical\n"
"{\n"
"  width: 20px;\n"
"  margin: 23px 5px 23px 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"  min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"  height: 20px;\n"
"  subcontrol-position: bottom;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"  height: 20px;\n"
"  subcontrol-position: top;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"  image: url(images/scrollbar_up_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical:pressed\n"
"{\n"
"  image: url(images/scrollbar_up_arrow_pressed.png);\n"
"}\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"  image: url(images/scrollbar_down_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::down-arrow:vertical:pressed\n"
"{\n"
"  image: url(images/scrollbar_down_arrow_pressed.png);\n"
"}\n"
"\n"
"/**** QScrollBar (disabled) ****/\n"
"QScrollBar:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QScrollBar::handle:disabled\n"
"{\n"
"  background-color: rgb(80,80,80);\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal:disabled\n"
"{\n"
"  image: url(images/scrollbar_left_arrow_disabled.png);\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal:disabled\n"
"{\n"
"  image: url(images/scrollbar_right_arrow_disabled.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical:disabled\n"
"{\n"
"  image: url(images/scrollbar_up_arrow_disabled.png);\n"
"}\n"
"\n"
"QScrollBar::down-arrow:vertical:disabled\n"
"{\n"
"  image: url(images/scrollbar_down_arrow_disabled.png);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QSlider (enabled) ****/\n"
"QSlider\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QSlider::groove\n"
"{\n"
"  border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(40,150,200), stop: 1 rgb(90,200,255));\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"/**** QSlider (horizontal) ****/\n"
"QSlider::groove:horizontal\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(160,160,160), stop: 1 rgb(80,80,80));\n"
"  height: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal\n"
"{\n"
"  margin: -6px 0;\n"
"  width: 16px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"/**** QSlider (vertical) ****/\n"
"QSlider::groove:vertical\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                    stop: 0 rgb(160,160,160), stop: 1 rgb(80,80,80));\n"
"  width: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical\n"
"{\n"
"  margin: 0 -6px;\n"
"  height: 16px;\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"}\n"
"\n"
"/**** QSlider (disabled) ****/\n"
"QSlider::handle:disabled\n"
"{\n"
"  background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                    stop: 0 rgb(160,160,160), stop: 1 rgb(120,120,120));\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QLabel (enabled) ****/\n"
"QLabel\n"
"{\n"
"  background-color: transparent;\n"
"  color: rgb(220,220,220);\n"
"  padding: 4px;\n"
"}\n"
"\n"
"/**** QLabel (disabled) ****/\n"
"QLabel\n"
"{\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QTextBrowser (enabled) ****/\n"
"QTextBrowser\n"
"{\n"
"  background-color: rgb(100,100,100);\n"
"  border: 1px solid rgb(20,20,20);\n"
"}\n"
"\n"
"/**** QTextBrowser (disabled) ****/\n"
"QTextBrowser:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QGraphicsView (enabled) ****/\n"
"QGraphicsView\n"
"{\n"
"  background-color: rgb(100,100,100);\n"
"  border: 1px solid rgb(20,20,20);\n"
"}\n"
"\n"
"/**** QGraphicsView (disabled) ****/\n"
"QGraphicsView:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QCalendarWidget (enabled) ****/\n"
"QCalendarWidget > QWidget\n"
"{\n"
"  background-color: rgb(60,60,60);\n"
"  border: 1px solid rgb(20,20,20);\n"
"}\n"
"\n"
"QCalendarWidget QToolButton\n"
"{\n"
"  border: transparent;\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QCalendarWidget QTableView\n"
"{\n"
"  border: transparent;\n"
"  background-color: rgb(140,140,140);\n"
"  selection-background-color: rgb(70,110,130);\n"
"  selection-color: white;\n"
"}\n"
"\n"
"/**** QCalendarWidget (disabled) ****/\n"
"QCalendarWidget > QWidget:disabled\n"
"{\n"
"  background-color: rgb(100,100,100);\n"
"  border-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:disabled\n"
"{\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QCalendarWidget QTableView:disabled\n"
"{\n"
"  background-color: rgb(160,160,160);\n"
"  selection-background-color: transparent;\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QLCDNumber (enabled) ****/\n"
"QLCDNumber\n"
"{\n"
"  background-color: rgb(40,40,40);\n"
"  border: 1px solid rgb(20,20,20);\n"
"}\n"
"\n"
"/**** QLCDNumber (disabled) ****/\n"
"QLCDNumber:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border: 1px solid rgb(60,60,60);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QProgressBar (enabled) ****/\n"
"QProgressBar\n"
"{\n"
"  background-color: rgb(40,40,40);\n"
"  background-color: rgb(20,60,80);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(220,220,220);\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"  margin: 1px;\n"
"  width: 4px;\n"
"}\n"
"\n"
"/**** QProgressBar (disabled) ****/\n"
"QProgressBar:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border: 1px solid rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QMenuBar (enabled) ****/\n"
"QMenuBar\n"
"{\n"
"  background-color: rgb(60,60,60);\n"
"  border: 1px solid transparent;\n"
"  border-bottom-color: rgb(80,80,80);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"  background-color: transparent;\n"
"  color: rgb(220,220,220);\n"
"  padding: 8px;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"  color: white;\n"
"}\n"
"\n"
"/**** QMenuBar (disabled) ****/\n"
"QMenuBar:disabled\n"
"{\n"
"  background-color: rgb(100,100,100);\n"
"  border-bottom-color: rgb(60,60,60);\n"
"}\n"
"\n"
"QMenuBar::item:disabled\n"
"{\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QMenu (enabled) ****/\n"
"QMenu\n"
"{\n"
"  background-color: rgb(60,60,60);\n"
"  color: rgb(220,220,220);\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"  background-color: rgb(70,110,130);\n"
"  color: white;\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QToolBar (enabled) ****/\n"
"QToolBar\n"
"{\n"
"  background-color: rgb(60,60,60);\n"
"  border: 1px outset rgb(120,120,120);\n"
"}\n"
"\n"
"QToolBar > QToolButton\n"
"{\n"
"  background-color: transparent;\n"
"  border: 1px solid transparent;\n"
"}\n"
"\n"
"/**** QToolBar (disabled) ****/\n"
"QToolBar:disabled\n"
"{\n"
"  background-color: rgb(100,100,100);\n"
"}\n"
"\n"
"QToolBar > QToolButton:disabled\n"
"{\n"
"  background-color: transparent;\n"
"  border: 1px solid transparent;\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QToolTip (enabled) ****/\n"
"QToolTip\n"
"{\n"
"  background-color: rgb(90,200,255);\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color: rgb(20,20,20);\n"
"  opacity: 255;\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QStatusBar (enabled) ****/\n"
"QStatusBar\n"
"{\n"
"  background-color: rgb(60,60,60);\n"
"  border: 1px solid transparent;\n"
"  color: rgb(220,220,220);\n"
"  border-top-color: rgb(80,80,80);\n"
"}\n"
"\n"
"/**** QStatusBar (disabled) ****/\n"
"QStatusBar:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border-top-color: rgb(60,60,60);\n"
"  color: rgb(40,40,40);\n"
"}\n"
"\n"
"/*********************************************************************************************************/\n"
"\n"
"/**** QSizeGrip (enabled) ****/\n"
"QSizeGrip\n"
"{\n"
"  background-color: transparent;\n"
"  image: url(images/sizegrip.png);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QSizeGrip:hover\n"
"{\n"
"  image: url(images/sizegrip_hover.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dep_1 = QtWidgets.QRadioButton(self.groupBox)
        self.dep_1.setObjectName("dep_1")
        self.verticalLayout.addWidget(self.dep_1)
        self.dep_2 = QtWidgets.QRadioButton(self.groupBox)
        self.dep_2.setObjectName("dep_2")
        self.verticalLayout.addWidget(self.dep_2)
        self.dep_3 = QtWidgets.QRadioButton(self.groupBox)
        self.dep_3.setObjectName("dep_3")
        self.verticalLayout.addWidget(self.dep_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 32))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Department "))
        self.dep_1.setText(_translate("MainWindow", "Dental"))
        self.dep_2.setText(_translate("MainWindow", "Otolaryngology"))
        self.dep_3.setText(_translate("MainWindow", "Radiology"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose"))
        self.comboBox.setItemText(1, _translate("MainWindow", "PM Report"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Daily Inspection Report"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Installation and Scrapping Report"))
        self.pushButton.setText(_translate("MainWindow", "SHOW"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Equipment_name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Brand"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Serial_number"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Installation_data"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Scrapping_data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Daily Inspaction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

